name: HungerGame
main: org.sobadfish.hunger.HungerGameMain
version: 1.0.3
api:
  - 1.0.11
  - 3.0.0
author: sobadfish
load: POSTWORLD
description: "饥饿游戏"

softdepend:
  - ScoreboardPlugin

loadbefore:
  - ScoreboardPlugin
